package com.shxseer.watch.algorithm.diseasereport.reportutils;

import com.shxseer.watch.algorithm.diseasetools.ScaleCompute;
import com.shxseer.watch.algorithm.wavetools.WaveDenty;
import com.shxseer.watch.algorithm.wavetools.WaveFormModel;
import com.shxseer.watch.common.Constant;
import com.shxseer.watch.common.SplitData;
import com.shxseer.watch.model.*;
import com.shxseer.watch.utils.IdUtils;

import java.util.*;

/**
 * 尺度值计算工具类
 * @author zhangliang
 * @since 2018-08-21 11:13
 */
public class DiseaseScaleUtils {

    /**
     * 计算所有特征值的尺度值
     * @param eigenValueMapList 前三组特征值对象的集合
     * @param userId 当前用户的id
     * @return
     */
    public static Map<String, Object> getDiseaseScaleValue(List<Map<String,Object>> eigenValueMapList, String userId){
        Map<String, Object> returnMap = new HashMap<String, Object>();
        DiseaseScaleValueOne diseaseScaleValueOne = new DiseaseScaleValueOne();
        DiseaseScaleValueTwo diseaseScaleValueTwo = new DiseaseScaleValueTwo();
        DiseaseScaleValueThree diseaseScaleValueThree = new DiseaseScaleValueThree();
        DiseaseScaleValueFour diseaseScaleValueFour = new DiseaseScaleValueFour();
        //给病症尺度值一、二、三、四对象的常规属性赋值
        String diseaseScaleValueOneId = IdUtils.uuid();
        diseaseScaleValueOne.setId(diseaseScaleValueOneId);
        Date nowDate = new Date();
        diseaseScaleValueOne.setCreateTime(nowDate);
        diseaseScaleValueOne.setUpdateTime(nowDate);
        diseaseScaleValueOne.setUserId(userId);
        diseaseScaleValueTwo.setId(IdUtils.uuid());
        diseaseScaleValueTwo.setDiseaseScaleValueOneId(diseaseScaleValueOneId);
        diseaseScaleValueThree.setId(IdUtils.uuid());
        diseaseScaleValueThree.setDiseaseScaleValueOneId(diseaseScaleValueOneId);
        diseaseScaleValueFour.setId(IdUtils.uuid());
        diseaseScaleValueFour.setDiseaseScaleValueOneId(diseaseScaleValueOneId);
        //给病症尺度值一、二、三、四对象的特征值相关的属性赋值
        List<Double> startValueList = new ArrayList<Double>();
        List<Double> startIndexList = new ArrayList<Double>();
        List<Double> endValueList = new ArrayList<Double>();
        List<Double> endIndexList = new ArrayList<Double>();
        List<Double> centerValueList = new ArrayList<Double>();
        List<Double> centerIndexList = new ArrayList<Double>();
        List<Double> downcenterValueList = new ArrayList<Double>();
        List<Double> downcenterIndexList = new ArrayList<Double>();
        List<Double> areaList = new ArrayList<Double>();
        List<Double> widthList = new ArrayList<Double>();
        List<Double> singleLengthList = new ArrayList<Double>();
        List<Double> speedList = new ArrayList<Double>();
        List<Double> aoneValueList = new ArrayList<Double>();
        List<Double> aoneIndexList = new ArrayList<Double>();
        List<Double> atwoValueList = new ArrayList<Double>();
        List<Double> atwoIndexList = new ArrayList<Double>();
        List<Double> athrValueList = new ArrayList<Double>();
        List<Double> athrIndexList = new ArrayList<Double>();
        List<Double> boneValueList = new ArrayList<Double>();
        List<Double> boneIndexList = new ArrayList<Double>();
        List<Double> btwoValueList = new ArrayList<Double>();
        List<Double> btwoIndexList = new ArrayList<Double>();
        List<Double> bthrValueList = new ArrayList<Double>();
        List<Double> bthrIndexList = new ArrayList<Double>();
        List<Double> coneValueList = new ArrayList<Double>();
        List<Double> coneIndexList = new ArrayList<Double>();
        List<Double> ctwoValueList = new ArrayList<Double>();
        List<Double> ctwoIndexList = new ArrayList<Double>();
        List<Double> aoneShallowUpList = new ArrayList<Double>();
        List<Double> aoneShallowDwonList = new ArrayList<Double>();
        List<Double> aoneCenterUpList = new ArrayList<Double>();
        List<Double> aoneCenterDwonList = new ArrayList<Double>();
        List<Double> aoneDeepUpList = new ArrayList<Double>();
        List<Double> aoneDeepDwonList = new ArrayList<Double>();
        List<Double> atwoShallowUpList = new ArrayList<Double>();
        List<Double> atwoShallowDwonList = new ArrayList<Double>();
        List<Double> atwoCenterUpList = new ArrayList<Double>();
        List<Double> atwoCenterDwonList = new ArrayList<Double>();
        List<Double> atwoDeepUpList = new ArrayList<Double>();
        List<Double> atwoDeepDwonList = new ArrayList<Double>();
        List<Double> athrShallowUpList = new ArrayList<Double>();
        List<Double> athrShallowDwonList = new ArrayList<Double>();
        List<Double> athrCenterUpList = new ArrayList<Double>();
        List<Double> athrCenterDwonList = new ArrayList<Double>();
        List<Double> athrDeepUpList = new ArrayList<Double>();
        List<Double> athrDeepDwonList = new ArrayList<Double>();
        List<Double> boneShallowUpList = new ArrayList<Double>();
        List<Double> boneShallowDwonList = new ArrayList<Double>();
        List<Double> boneCenterUpList = new ArrayList<Double>();
        List<Double> boneCenterDwonList = new ArrayList<Double>();
        List<Double> boneDeepUpList = new ArrayList<Double>();
        List<Double> boneDeepDwonList = new ArrayList<Double>();
        List<Double> btwoShallowUpList = new ArrayList<Double>();
        List<Double> btwoShallowDwonList = new ArrayList<Double>();
        List<Double> btwoCenterUpList = new ArrayList<Double>();
        List<Double> btwoCenterDwonList = new ArrayList<Double>();
        List<Double> btwoDeepUpList = new ArrayList<Double>();
        List<Double> btwoDeepDwonList = new ArrayList<Double>();
        List<Double> bthrShallowUpList = new ArrayList<Double>();
        List<Double> bthrShallowDwonList = new ArrayList<Double>();
        List<Double> bthrCenterUpList = new ArrayList<Double>();
        List<Double> bthrCenterDwonList = new ArrayList<Double>();
        List<Double> bthrDeepUpList = new ArrayList<Double>();
        List<Double> bthrDeepDwonList = new ArrayList<Double>();
        List<Double> coneShallowUpList = new ArrayList<Double>();
        List<Double> coneShallowDwonList = new ArrayList<Double>();
        List<Double> coneCenterUpList = new ArrayList<Double>();
        List<Double> coneCenterDwonList = new ArrayList<Double>();
        List<Double> coneDeepUpList = new ArrayList<Double>();
        List<Double> coneDeepDwonList = new ArrayList<Double>();
        List<Double> ctwoShallowUpList = new ArrayList<Double>();
        List<Double> ctwoShallowDwonList = new ArrayList<Double>();
        List<Double> ctwoCenterUpList = new ArrayList<Double>();
        List<Double> ctwoCenterDwonList = new ArrayList<Double>();
        List<Double> ctwoDeepUpList = new ArrayList<Double>();
        List<Double> ctwoDeepDwonList = new ArrayList<Double>();
        List<Double> riseTimeList = new ArrayList<Double>();
        List<Double> fallTimeList = new ArrayList<Double>();
        List<Double> heartRateList = new ArrayList<Double>();
        List<Double> singleWaveLengthList = new ArrayList<Double>();
        List<Double> averagePressList = new ArrayList<Double>();
        List<Double> athreeSpeedList = new ArrayList<>();
        List<Double> bthreeSpeedList = new ArrayList<>();
        List<Double> bsconeSpeedList = new ArrayList<>();
        List<Double> kvalueList = new ArrayList<>();

        String regex = Constant.EIGENVALUE_SPLIT;

        for (Map<String,Object> eigenValueMap : eigenValueMapList) {
            EigenValueOne eigenValueOne = (EigenValueOne) eigenValueMap.get("eigenValueOne");
            EigenValueTwo eigenValueTwo = (EigenValueTwo) eigenValueMap.get("eigenValueTwo");
            EigenValueThree eigenValueThree = (EigenValueThree) eigenValueMap.get("eigenValueThree");
            EigenValueFour eigenValueFour = (EigenValueFour) eigenValueMap.get("eigenValueFour");
            EigenValueFive eigenValueFive = (EigenValueFive) eigenValueMap.get("eigenValueFive");
            startValueList.add(SplitData.countDoubleListAvg(SplitData.stringToDoubleList(eigenValueOne.getStartValue(), regex)));
            startIndexList.add(SplitData.countDoubleListAvg(SplitData.stringToDoubleList(eigenValueOne.getStartIndex(), regex)));
            endValueList.add(SplitData.countDoubleListAvg(SplitData.stringToDoubleList(eigenValueOne.getEndValue(), regex)));
            endIndexList.add(SplitData.countDoubleListAvg(SplitData.stringToDoubleList(eigenValueOne.getEndIndex(), regex)));
            centerValueList.add(SplitData.countDoubleListAvg(SplitData.stringToDoubleList(eigenValueOne.getCenterValue(), regex)));
            centerIndexList.add(SplitData.countDoubleListAvg(SplitData.stringToDoubleList(eigenValueOne.getCenterIndex(), regex)));
            downcenterValueList.add(SplitData.countDoubleListAvg(SplitData.stringToDoubleList(eigenValueOne.getDowncenterValue(), regex)));
            downcenterIndexList.add(SplitData.countDoubleListAvg(SplitData.stringToDoubleList(eigenValueOne.getDowncenterIndex(), regex)));
            areaList.add(SplitData.countDoubleListAvg(SplitData.stringToDoubleList(eigenValueOne.getArea(), regex)));
            widthList.add(SplitData.countDoubleListAvg(SplitData.stringToDoubleList(eigenValueTwo.getWidth(), regex)));
            singleLengthList.add(SplitData.countDoubleListAvg(SplitData.stringToDoubleList(eigenValueTwo.getSingleLength(), regex)));
            speedList.add(SplitData.countDoubleListAvg(SplitData.stringToDoubleList(eigenValueTwo.getSpeed(), regex)));
            aoneValueList.add(SplitData.countDoubleListAvg(SplitData.stringToDoubleList(eigenValueTwo.getAoneValue(), regex)));
            aoneIndexList.add(SplitData.countDoubleListAvg(SplitData.stringToDoubleList(eigenValueTwo.getAoneIndex(), regex)));
            atwoValueList.add(SplitData.countDoubleListAvg(SplitData.stringToDoubleList(eigenValueTwo.getAtwoValue(), regex)));
            atwoIndexList.add(SplitData.countDoubleListAvg(SplitData.stringToDoubleList(eigenValueTwo.getAtwoIndex(), regex)));
            athrValueList.add(SplitData.countDoubleListAvg(SplitData.stringToDoubleList(eigenValueTwo.getAthrValue(), regex)));
            athrIndexList.add(SplitData.countDoubleListAvg(SplitData.stringToDoubleList(eigenValueTwo.getAthrIndex(), regex)));
            boneValueList.add(SplitData.countDoubleListAvg(SplitData.stringToDoubleList(eigenValueTwo.getBoneValue(), regex)));
            boneIndexList.add(SplitData.countDoubleListAvg(SplitData.stringToDoubleList(eigenValueTwo.getBoneIndex(), regex)));
            btwoValueList.add(SplitData.countDoubleListAvg(SplitData.stringToDoubleList(eigenValueTwo.getBtwoValue(), regex)));
            btwoIndexList.add(SplitData.countDoubleListAvg(SplitData.stringToDoubleList(eigenValueTwo.getBtwoIndex(), regex)));
            bthrValueList.add(SplitData.countDoubleListAvg(SplitData.stringToDoubleList(eigenValueTwo.getBthrValue(), regex)));
            bthrIndexList.add(SplitData.countDoubleListAvg(SplitData.stringToDoubleList(eigenValueTwo.getBthrIndex(), regex)));
            coneValueList.add(SplitData.countDoubleListAvg(SplitData.stringToDoubleList(eigenValueTwo.getConeValue(), regex)));
            coneIndexList.add(SplitData.countDoubleListAvg(SplitData.stringToDoubleList(eigenValueTwo.getConeIndex(), regex)));
            ctwoValueList.add(SplitData.countDoubleListAvg(SplitData.stringToDoubleList(eigenValueTwo.getCtwoValue(), regex)));
            ctwoIndexList.add(SplitData.countDoubleListAvg(SplitData.stringToDoubleList(eigenValueThree.getCtwoIndex(), regex)));
            aoneShallowUpList.add((double) SplitData.countIntegerListAvg(SplitData.stringToIntegerList(eigenValueThree.getAoneShallowUp(), regex)));
            aoneShallowDwonList.add((double) SplitData.countIntegerListAvg(SplitData.stringToIntegerList(eigenValueThree.getAoneShallowDwon(), regex)));
            aoneCenterUpList.add((double) SplitData.countIntegerListAvg(SplitData.stringToIntegerList(eigenValueThree.getAoneCenterUp(), regex)));
            aoneCenterDwonList.add((double) SplitData.countIntegerListAvg(SplitData.stringToIntegerList(eigenValueThree.getAoneCenterDwon(), regex)));
            aoneDeepUpList.add((double) SplitData.countIntegerListAvg(SplitData.stringToIntegerList(eigenValueThree.getAoneDeepUp(), regex)));
            aoneDeepDwonList.add((double) SplitData.countIntegerListAvg(SplitData.stringToIntegerList(eigenValueThree.getAoneDeepDwon(), regex)));
            atwoShallowUpList.add((double) SplitData.countIntegerListAvg(SplitData.stringToIntegerList(eigenValueThree.getAtwoShallowUp(), regex)));
            atwoShallowDwonList.add((double) SplitData.countIntegerListAvg(SplitData.stringToIntegerList(eigenValueThree.getAtwoShallowDwon(), regex)));
            atwoCenterUpList.add((double) SplitData.countIntegerListAvg(SplitData.stringToIntegerList(eigenValueThree.getAtwoCenterUp(), regex)));
            atwoCenterDwonList.add((double) SplitData.countIntegerListAvg(SplitData.stringToIntegerList(eigenValueThree.getAtwoCenterDwon(), regex)));
            atwoDeepUpList.add((double) SplitData.countIntegerListAvg(SplitData.stringToIntegerList(eigenValueThree.getAtwoDeepUp(), regex)));
            atwoDeepDwonList.add((double) SplitData.countIntegerListAvg(SplitData.stringToIntegerList(eigenValueThree.getAtwoDeepDwon(), regex)));
            athrShallowUpList.add((double) SplitData.countIntegerListAvg(SplitData.stringToIntegerList(eigenValueThree.getAthrShallowUp(), regex)));
            athrShallowDwonList.add((double) SplitData.countIntegerListAvg(SplitData.stringToIntegerList(eigenValueThree.getAthrShallowDwon(), regex)));
            athrCenterUpList.add((double) SplitData.countIntegerListAvg(SplitData.stringToIntegerList(eigenValueThree.getAthrCenterUp(), regex)));
            athrCenterDwonList.add((double) SplitData.countIntegerListAvg(SplitData.stringToIntegerList(eigenValueThree.getAthrCenterDwon(), regex)));
            athrDeepUpList.add((double) SplitData.countIntegerListAvg(SplitData.stringToIntegerList(eigenValueFour.getAthrDeepUp(), regex)));
            athrDeepDwonList.add((double) SplitData.countIntegerListAvg(SplitData.stringToIntegerList(eigenValueFour.getAthrDeepDwon(), regex)));
            boneShallowUpList.add((double) SplitData.countIntegerListAvg(SplitData.stringToIntegerList(eigenValueFour.getBoneShallowUp(), regex)));
            boneShallowDwonList.add((double) SplitData.countIntegerListAvg(SplitData.stringToIntegerList(eigenValueFour.getBoneShallowDwon(), regex)));
            boneCenterUpList.add((double) SplitData.countIntegerListAvg(SplitData.stringToIntegerList(eigenValueFour.getBoneCenterUp(), regex)));
            boneCenterDwonList.add((double) SplitData.countIntegerListAvg(SplitData.stringToIntegerList(eigenValueFour.getBoneCenterDwon(), regex)));
            boneDeepUpList.add((double) SplitData.countIntegerListAvg(SplitData.stringToIntegerList(eigenValueFour.getBoneDeepUp(), regex)));
            boneDeepDwonList.add((double) SplitData.countIntegerListAvg(SplitData.stringToIntegerList(eigenValueFour.getBoneDeepDwon(), regex)));
            btwoShallowUpList.add((double) SplitData.countIntegerListAvg(SplitData.stringToIntegerList(eigenValueFour.getBtwoShallowUp(), regex)));
            btwoShallowDwonList.add((double) SplitData.countIntegerListAvg(SplitData.stringToIntegerList(eigenValueFour.getBtwoShallowDwon(), regex)));
            btwoCenterUpList.add((double) SplitData.countIntegerListAvg(SplitData.stringToIntegerList(eigenValueFour.getBtwoCenterUp(), regex)));
            btwoCenterDwonList.add((double) SplitData.countIntegerListAvg(SplitData.stringToIntegerList(eigenValueFour.getBtwoCenterDwon(), regex)));
            btwoDeepUpList.add((double) SplitData.countIntegerListAvg(SplitData.stringToIntegerList(eigenValueFour.getBtwoDeepUp(), regex)));
            btwoDeepDwonList.add((double) SplitData.countIntegerListAvg(SplitData.stringToIntegerList(eigenValueFour.getBtwoDeepDwon(), regex)));
            bthrShallowUpList.add((double) SplitData.countIntegerListAvg(SplitData.stringToIntegerList(eigenValueFour.getBthrShallowUp(), regex)));
            bthrShallowDwonList.add((double) SplitData.countIntegerListAvg(SplitData.stringToIntegerList(eigenValueFour.getBthrShallowDwon(), regex)));
            bthrCenterUpList.add((double) SplitData.countIntegerListAvg(SplitData.stringToIntegerList(eigenValueFour.getBthrCenterUp(), regex)));
            bthrCenterDwonList.add((double) SplitData.countIntegerListAvg(SplitData.stringToIntegerList(eigenValueFive.getBthrCenterDwon(), regex)));
            bthrDeepUpList.add((double) SplitData.countIntegerListAvg(SplitData.stringToIntegerList(eigenValueFive.getBthrDeepUp(), regex)));
            bthrDeepDwonList.add((double) SplitData.countIntegerListAvg(SplitData.stringToIntegerList(eigenValueFive.getBthrDeepDwon(), regex)));
            coneShallowUpList.add((double) SplitData.countIntegerListAvg(SplitData.stringToIntegerList(eigenValueFive.getConeShallowUp(), regex)));
            coneShallowDwonList.add((double) SplitData.countIntegerListAvg(SplitData.stringToIntegerList(eigenValueFive.getConeShallowDwon(), regex)));
            coneCenterUpList.add((double) SplitData.countIntegerListAvg(SplitData.stringToIntegerList(eigenValueFive.getConeCenterUp(), regex)));
            coneCenterDwonList.add((double) SplitData.countIntegerListAvg(SplitData.stringToIntegerList(eigenValueFive.getConeCenterDwon(), regex)));
            coneDeepUpList.add((double) SplitData.countIntegerListAvg(SplitData.stringToIntegerList(eigenValueFive.getConeDeepUp(), regex)));
            coneDeepDwonList.add((double) SplitData.countIntegerListAvg(SplitData.stringToIntegerList(eigenValueFive.getConeDeepDwon(), regex)));
            ctwoShallowUpList.add((double) SplitData.countIntegerListAvg(SplitData.stringToIntegerList(eigenValueFive.getCtwoShallowUp(), regex)));
            ctwoShallowDwonList.add((double) SplitData.countIntegerListAvg(SplitData.stringToIntegerList(eigenValueFive.getCtwoShallowDwon(), regex)));
            ctwoCenterUpList.add((double) SplitData.countIntegerListAvg(SplitData.stringToIntegerList(eigenValueFive.getCtwoCenterUp(), regex)));
            ctwoCenterDwonList.add((double) SplitData.countIntegerListAvg(SplitData.stringToIntegerList(eigenValueFive.getCtwoCenterDwon(), regex)));
            ctwoDeepUpList.add((double) SplitData.countIntegerListAvg(SplitData.stringToIntegerList(eigenValueFive.getCtwoDeepUp(), regex)));
            ctwoDeepDwonList.add((double) SplitData.countIntegerListAvg(SplitData.stringToIntegerList(eigenValueFive.getCtwoDeepDwon(), regex)));
            riseTimeList.add(SplitData.countDoubleListAvg(SplitData.stringToDoubleList(eigenValueFour.getRiseTime(), regex)));
            fallTimeList.add(SplitData.countDoubleListAvg(SplitData.stringToDoubleList(eigenValueFour.getFallTime(), regex)));
            heartRateList.add((double) SplitData.countIntegerListAvg(SplitData.stringToIntegerList(eigenValueOne.getHeartRate(), regex)));
            singleWaveLengthList.add((double) SplitData.countIntegerListAvg(SplitData.stringToIntegerList(eigenValueOne.getSingleWaveLength(), regex)));
            averagePressList.add(eigenValueFive.getAveragePress());
            athreeSpeedList.add(SplitData.countDoubleListAvg(SplitData.stringToDoubleList(eigenValueFive.getAthreeSpeed(), regex)));
            bthreeSpeedList.add(SplitData.countDoubleListAvg(SplitData.stringToDoubleList(eigenValueFive.getBthreeSpeed(), regex)));
            bsconeSpeedList.add(SplitData.countDoubleListAvg(SplitData.stringToDoubleList(eigenValueFive.getBsconeSpeed(), regex)));
            kvalueList.add(eigenValueOne.getKvalue());
        }
        diseaseScaleValueOne.setStartValueScale(ScaleCompute.getScaleSugarValue(startValueList));
        diseaseScaleValueOne.setStartIndexScale(ScaleCompute.getScaleSugarValue(startIndexList));
        diseaseScaleValueOne.setEndValueScale(ScaleCompute.getScaleSugarValue(endValueList));
        diseaseScaleValueOne.setEndIndexScale(ScaleCompute.getScaleSugarValue(endIndexList));
        diseaseScaleValueOne.setCenterValueScale(ScaleCompute.getScaleSugarValue(centerValueList));
        diseaseScaleValueOne.setCenterIndexScale(ScaleCompute.getScaleSugarValue(centerIndexList));
        diseaseScaleValueOne.setDowncenterValueScale(ScaleCompute.getScaleSugarValue(downcenterValueList));
        diseaseScaleValueOne.setDowncenterIndexScale(ScaleCompute.getScaleSugarValue(downcenterIndexList));
        diseaseScaleValueOne.setAreScale(ScaleCompute.getScaleSugarValue(areaList));
        diseaseScaleValueOne.setWidthScale(ScaleCompute.getScaleSugarValue(widthList));
        diseaseScaleValueOne.setSingleLengthScale(ScaleCompute.getScaleSugarValue(singleLengthList));
        diseaseScaleValueOne.setSpeedScale(ScaleCompute.getScaleSugarValue(speedList));
        diseaseScaleValueOne.setAoneValueScale(ScaleCompute.getScaleSugarValue(aoneValueList));
        diseaseScaleValueOne.setAoneIndexScale(ScaleCompute.getScaleSugarValue(aoneIndexList));
        diseaseScaleValueOne.setAtwoValueScale(ScaleCompute.getScaleSugarValue(atwoValueList));
        diseaseScaleValueOne.setAtwoIndexScale(ScaleCompute.getScaleSugarValue(atwoIndexList));
        diseaseScaleValueOne.setAthrValueScale(ScaleCompute.getScaleSugarValue(athrValueList));
        diseaseScaleValueOne.setAthrIndexScale(ScaleCompute.getScaleSugarValue(athrIndexList));
        diseaseScaleValueOne.setBoneValueScale(ScaleCompute.getScaleSugarValue(boneValueList));
        diseaseScaleValueOne.setBoneIndexScale(ScaleCompute.getScaleSugarValue(boneIndexList));
        diseaseScaleValueTwo.setBtwoValueScale(ScaleCompute.getScaleSugarValue(btwoValueList));
        diseaseScaleValueTwo.setBtwoIndexScale(ScaleCompute.getScaleSugarValue(btwoIndexList));
        diseaseScaleValueTwo.setBthrValueScale(ScaleCompute.getScaleSugarValue(bthrValueList));
        diseaseScaleValueTwo.setBthrIndexScale(ScaleCompute.getScaleSugarValue(bthrIndexList));
        diseaseScaleValueTwo.setConeValueScale(ScaleCompute.getScaleSugarValue(coneValueList));
        diseaseScaleValueTwo.setConeIndexScale(ScaleCompute.getScaleSugarValue(coneIndexList));
        diseaseScaleValueTwo.setCtwoValueScale(ScaleCompute.getScaleSugarValue(ctwoValueList));
        diseaseScaleValueTwo.setCtwoIndexScale(ScaleCompute.getScaleSugarValue(ctwoIndexList));
        diseaseScaleValueTwo.setAoneShallowUpScale(ScaleCompute.getScaleSugarValue(aoneShallowUpList));
        diseaseScaleValueTwo.setAoneShallowDwonScale(ScaleCompute.getScaleSugarValue(aoneShallowDwonList));
        diseaseScaleValueTwo.setAoneCenterUpScale(ScaleCompute.getScaleSugarValue(aoneCenterUpList));
        diseaseScaleValueTwo.setAoneCenterDwonScale(ScaleCompute.getScaleSugarValue(aoneCenterDwonList));
        diseaseScaleValueTwo.setAoneDeepUpScale(ScaleCompute.getScaleSugarValue(aoneDeepUpList));
        diseaseScaleValueTwo.setAoneDeepDwonScale(ScaleCompute.getScaleSugarValue(aoneDeepDwonList));
        diseaseScaleValueTwo.setAtwoShallowUpScale(ScaleCompute.getScaleSugarValue(atwoShallowUpList));
        diseaseScaleValueTwo.setAtwoShallowDwonScale(ScaleCompute.getScaleSugarValue(atwoShallowDwonList));
        diseaseScaleValueTwo.setAtwoCenterUpScale(ScaleCompute.getScaleSugarValue(atwoCenterUpList));
        diseaseScaleValueTwo.setAtwoCenterDwonScale(ScaleCompute.getScaleSugarValue(atwoCenterDwonList));
        diseaseScaleValueTwo.setAtwoDeepUpScale(ScaleCompute.getScaleSugarValue(atwoDeepUpList));
        diseaseScaleValueTwo.setAtwoDeepDwonScale(ScaleCompute.getScaleSugarValue(atwoDeepDwonList));
        diseaseScaleValueTwo.setAthrShallowUpScale(ScaleCompute.getScaleSugarValue(athrShallowUpList));
        diseaseScaleValueTwo.setAthrShallowDwonScale(ScaleCompute.getScaleSugarValue(athrShallowDwonList));
        diseaseScaleValueTwo.setAthrCenterUpScale(ScaleCompute.getScaleSugarValue(athrCenterUpList));
        diseaseScaleValueTwo.setAthrCenterDwonScale(ScaleCompute.getScaleSugarValue(athrCenterDwonList));
        diseaseScaleValueTwo.setAthrDeepUpScale(ScaleCompute.getScaleSugarValue(athrDeepUpList));
        diseaseScaleValueThree.setBoneShallowUpScale(ScaleCompute.getScaleSugarValue(boneShallowUpList));
        diseaseScaleValueThree.setBoneShallowDwonScale(ScaleCompute.getScaleSugarValue(boneShallowDwonList));
        diseaseScaleValueThree.setBoneCenterUpScale(ScaleCompute.getScaleSugarValue(boneCenterUpList));
        diseaseScaleValueThree.setBoneCenterDwonScale(ScaleCompute.getScaleSugarValue(boneCenterDwonList));
        diseaseScaleValueThree.setBoneDeepUpScale(ScaleCompute.getScaleSugarValue(boneDeepUpList));
        diseaseScaleValueThree.setBoneDeepDwonScale(ScaleCompute.getScaleSugarValue(boneDeepDwonList));
        diseaseScaleValueThree.setBtwoShallowUpScale(ScaleCompute.getScaleSugarValue(btwoShallowUpList));
        diseaseScaleValueThree.setBtwoShallowDwonScale(ScaleCompute.getScaleSugarValue(btwoShallowDwonList));
        diseaseScaleValueThree.setBtwoCenterUpScale(ScaleCompute.getScaleSugarValue(btwoCenterUpList));
        diseaseScaleValueThree.setBtwoCenterDwonScale(ScaleCompute.getScaleSugarValue(btwoCenterDwonList));
        diseaseScaleValueThree.setBtwoDeepUpScale(ScaleCompute.getScaleSugarValue(btwoDeepUpList));
        diseaseScaleValueThree.setBtwoDeepDwonScale(ScaleCompute.getScaleSugarValue(btwoDeepDwonList));
        diseaseScaleValueThree.setBthrShallowUpScale(ScaleCompute.getScaleSugarValue(bthrShallowUpList));
        diseaseScaleValueThree.setBthrShallowDwonScale(ScaleCompute.getScaleSugarValue(bthrShallowDwonList));
        diseaseScaleValueThree.setBthrCenterUpScale(ScaleCompute.getScaleSugarValue(bthrCenterUpList));
        diseaseScaleValueThree.setBthrCenterDwonScale(ScaleCompute.getScaleSugarValue(bthrCenterDwonList));
        diseaseScaleValueThree.setBthrDeepUpScale(ScaleCompute.getScaleSugarValue(bthrDeepUpList));
        diseaseScaleValueThree.setBthrDeepDwonScale(ScaleCompute.getScaleSugarValue(bthrDeepDwonList));
        diseaseScaleValueThree.setConeShallowUpScale(ScaleCompute.getScaleSugarValue(coneShallowUpList));
        diseaseScaleValueThree.setConeShallowDwonScale(ScaleCompute.getScaleSugarValue(coneShallowDwonList));
        diseaseScaleValueThree.setConeCenterUpScale(ScaleCompute.getScaleSugarValue(coneCenterUpList));
        diseaseScaleValueThree.setConeCenterDwonScale(ScaleCompute.getScaleSugarValue(coneCenterDwonList));
        diseaseScaleValueThree.setConeDeepUpScale(ScaleCompute.getScaleSugarValue(coneDeepUpList));
        diseaseScaleValueThree.setConeDeepDwonScale(ScaleCompute.getScaleSugarValue(coneDeepDwonList));
        diseaseScaleValueThree.setCtwoShallowUpScale(ScaleCompute.getScaleSugarValue(ctwoShallowUpList));
        diseaseScaleValueThree.setCtwoShallowDwonScale(ScaleCompute.getScaleSugarValue(ctwoShallowDwonList));
        diseaseScaleValueThree.setCtwoCenterUpScale(ScaleCompute.getScaleSugarValue(ctwoCenterUpList));
        diseaseScaleValueThree.setCtwoCenterDwonScale(ScaleCompute.getScaleSugarValue(ctwoCenterDwonList));
        diseaseScaleValueThree.setCtwoDeepUpScale(ScaleCompute.getScaleSugarValue(ctwoDeepUpList));
        diseaseScaleValueThree.setCtwoDeepDwonScale(ScaleCompute.getScaleSugarValue(ctwoDeepDwonList));
        diseaseScaleValueTwo.setUpTimeScale(ScaleCompute.getScaleSugarValue(riseTimeList));
        diseaseScaleValueTwo.setDownTimeScale(ScaleCompute.getScaleSugarValue(fallTimeList));
        diseaseScaleValueTwo.setHertrateScale(ScaleCompute.getScaleSugarValue(heartRateList));
        diseaseScaleValueTwo.setSingleWaveLengthScale(ScaleCompute.getScaleSugarValue(singleWaveLengthList));
        diseaseScaleValueOne.setAveragePressScale(ScaleCompute.getScaleSugarValue(averagePressList));
        diseaseScaleValueFour.setAthreeSpeedScale(ScaleCompute.getScaleSugarValue(athreeSpeedList));
        diseaseScaleValueFour.setBthreeSpeedScale(ScaleCompute.getScaleSugarValue(bthreeSpeedList));
        diseaseScaleValueFour.setBsconeSpeedScale(ScaleCompute.getScaleSugarValue(bsconeSpeedList));
        diseaseScaleValueFour.setKvalueScale(ScaleCompute.getScaleSugarValue(kvalueList));
        //将三个病症尺度值对象返回
        returnMap.put("diseaseScaleValueOne", diseaseScaleValueOne);
        returnMap.put("diseaseScaleValueTwo", diseaseScaleValueTwo);
        returnMap.put("diseaseScaleValueThree", diseaseScaleValueThree);
        returnMap.put("diseaseScaleValueFour", diseaseScaleValueFour);
        return returnMap;
    }

    /**
     * 将尺度值三个对象转为算法WaveFormModel类对象
     * @param diseaseScaleMap
     * @return
     */
    public static WaveFormModel diseaseScaleToWaveFormModel(Map<String, Object> diseaseScaleMap){
        WaveFormModel waveFormModel = new WaveFormModel();
        WaveDenty waveDenty=new WaveDenty();
        DiseaseScaleValueOne diseaseScaleValueOne = (DiseaseScaleValueOne) diseaseScaleMap.get("diseaseScaleValueOne");
        DiseaseScaleValueTwo diseaseScaleValueTwo = (DiseaseScaleValueTwo) diseaseScaleMap.get("diseaseScaleValueTwo");
        DiseaseScaleValueThree diseaseScaleValueThree = (DiseaseScaleValueThree) diseaseScaleMap.get("diseaseScaleValueThree");
        DiseaseScaleValueFour diseaseScaleValueFour = (DiseaseScaleValueFour) diseaseScaleMap.get("diseaseScaleValueFour");
        waveFormModel.setHertrate((int) diseaseScaleValueTwo.getHertrateScale());
        waveFormModel.setStartValue(diseaseScaleValueOne.getStartValueScale());
        waveFormModel.setStartIndex(diseaseScaleValueOne.getStartIndexScale());
        waveFormModel.setEndValue(diseaseScaleValueOne.getEndValueScale());
        waveFormModel.setEndIndex(diseaseScaleValueOne.getEndIndexScale());
        waveFormModel.setCenterValue(diseaseScaleValueOne.getCenterValueScale());
        waveFormModel.setCenterIndex(diseaseScaleValueOne.getCenterIndexScale());
        waveFormModel.setDowncenterValue(diseaseScaleValueOne.getDowncenterValueScale());
        waveFormModel.setDowncenterIndex(diseaseScaleValueOne.getDowncenterIndexScale());
        waveFormModel.setAre(diseaseScaleValueOne.getAreScale());
        waveFormModel.setWidth(diseaseScaleValueOne.getWidthScale());
        waveFormModel.setSingleLength(diseaseScaleValueOne.getSingleLengthScale());
        waveFormModel.setSpeed(diseaseScaleValueOne.getSpeedScale());
        waveFormModel.setAoneValue(diseaseScaleValueOne.getAoneValueScale());
        waveFormModel.setAoneIndex(diseaseScaleValueOne.getAoneIndexScale());
        waveFormModel.setAtwoValue(diseaseScaleValueOne.getAtwoValueScale());
        waveFormModel.setAtwoIndex(diseaseScaleValueOne.getAtwoIndexScale());
        waveFormModel.setAthrValue(diseaseScaleValueOne.getAthrValueScale());
        waveFormModel.setAthrIndex(diseaseScaleValueOne.getAthrIndexScale());
        waveFormModel.setBoneValue(diseaseScaleValueOne.getBoneValueScale());
        waveFormModel.setBoneIndex(diseaseScaleValueOne.getBoneIndexScale());
        waveFormModel.setBtwoValue(diseaseScaleValueTwo.getBtwoValueScale());
        waveFormModel.setBtwoIndex(diseaseScaleValueTwo.getBtwoIndexScale());
        waveFormModel.setBthrValue(diseaseScaleValueTwo.getBthrValueScale());
        waveFormModel.setBthrIndex(diseaseScaleValueTwo.getBthrIndexScale());
        waveFormModel.setConeValue(diseaseScaleValueTwo.getConeValueScale());
        waveFormModel.setConeIndex(diseaseScaleValueTwo.getConeIndexScale());
        waveFormModel.setCtwoValue(diseaseScaleValueTwo.getCtwoValueScale());
        waveFormModel.setCtwoIndex(diseaseScaleValueTwo.getCtwoIndexScale());
        waveDenty.setAoneShallowUp((int) diseaseScaleValueTwo.getAoneShallowUpScale());
        waveDenty.setAoneShallowDwon((int) diseaseScaleValueTwo.getAoneShallowDwonScale());
        waveDenty.setAoneCenterUp((int) diseaseScaleValueTwo.getAoneCenterUpScale());
        waveDenty.setAoneCenterDwon((int) diseaseScaleValueTwo.getAoneCenterDwonScale());
        waveDenty.setAoneDeepUp((int) diseaseScaleValueTwo.getAoneDeepUpScale());
        waveDenty.setAoneDeepDwon((int) diseaseScaleValueTwo.getAoneDeepDwonScale());
        waveDenty.setAtwoShallowUp((int) diseaseScaleValueTwo.getAtwoShallowUpScale());
        waveDenty.setAtwoShallowDwon((int) diseaseScaleValueTwo.getAtwoShallowDwonScale());
        waveDenty.setAtwoCenterUp((int) diseaseScaleValueTwo.getAtwoCenterUpScale());
        waveDenty.setAtwoCenterDwon((int) diseaseScaleValueTwo.getAtwoCenterDwonScale());
        waveDenty.setAtwoDeepUp((int) diseaseScaleValueTwo.getAtwoDeepUpScale());
        waveDenty.setAtwoDeepDwon((int) diseaseScaleValueTwo.getAtwoDeepDwonScale());
        waveDenty.setAthrShallowUp((int) diseaseScaleValueTwo.getAthrShallowUpScale());
        waveDenty.setAthrShallowDwon((int) diseaseScaleValueTwo.getAthrShallowDwonScale());
        waveDenty.setAthrCenterUp((int) diseaseScaleValueTwo.getAthrCenterUpScale());
        waveDenty.setAthrCenterDwon((int) diseaseScaleValueTwo.getAthrCenterDwonScale());
        waveDenty.setAthrDeepUp((int) diseaseScaleValueTwo.getAthrDeepUpScale());
        waveDenty.setAthrDeepDwon((int) diseaseScaleValueTwo.getAthrDeepDwonScale());
        waveDenty.setBoneShallowUp((int) diseaseScaleValueThree.getBoneShallowUpScale());
        waveDenty.setBoneShallowDwon((int) diseaseScaleValueThree.getBoneCenterDwonScale());
        waveDenty.setBoneCenterUp((int) diseaseScaleValueThree.getBoneCenterUpScale());
        waveDenty.setBoneCenterDwon((int) diseaseScaleValueThree.getBoneCenterDwonScale());
        waveDenty.setBoneDeepUp((int) diseaseScaleValueThree.getBoneDeepUpScale());
        waveDenty.setBoneDeepDwon((int) diseaseScaleValueThree.getBoneDeepDwonScale());
        waveDenty.setBtwoShallowUp((int) diseaseScaleValueThree.getBtwoShallowUpScale());
        waveDenty.setBtwoShallowDwon((int) diseaseScaleValueThree.getBtwoShallowDwonScale());
        waveDenty.setBtwoCenterUp((int) diseaseScaleValueThree.getBtwoCenterUpScale());
        waveDenty.setBtwoCenterDwon((int) diseaseScaleValueThree.getBthrCenterDwonScale());
        waveDenty.setBtwoDeepUp((int) diseaseScaleValueThree.getBtwoDeepUpScale());
        waveDenty.setBtwoDeepDwon((int) diseaseScaleValueThree.getBtwoDeepDwonScale());
        waveDenty.setBthrShallowUp((int) diseaseScaleValueThree.getBthrShallowUpScale());
        waveDenty.setBthrShallowDwon((int) diseaseScaleValueThree.getBthrShallowDwonScale());
        waveDenty.setBthrCenterUp((int) diseaseScaleValueThree.getBthrCenterUpScale());
        waveDenty.setBthrCenterDwon((int) diseaseScaleValueThree.getBthrCenterDwonScale());
        waveDenty.setBthrDeepUp((int) diseaseScaleValueThree.getBthrDeepUpScale());
        waveDenty.setBthrDeepDwon((int) diseaseScaleValueThree.getBthrDeepDwonScale());
        waveDenty.setConeShallowUp((int) diseaseScaleValueThree.getConeShallowUpScale());
        waveDenty.setConeShallowDwon((int) diseaseScaleValueThree.getConeShallowDwonScale());
        waveDenty.setConeCenterUp((int) diseaseScaleValueThree.getConeCenterUpScale());
        waveDenty.setConeCenterDwon((int) diseaseScaleValueThree.getConeCenterDwonScale());
        waveDenty.setConeDeepUp((int) diseaseScaleValueThree.getConeDeepUpScale());
        waveDenty.setConeDeepDwon((int) diseaseScaleValueThree.getConeDeepDwonScale());
        waveDenty.setCtwoShallowUp((int) diseaseScaleValueThree.getCtwoShallowUpScale());
        waveDenty.setCtwoShallowDwon((int) diseaseScaleValueThree.getCtwoShallowDwonScale());
        waveDenty.setCtwoCenterUp((int) diseaseScaleValueThree.getCtwoCenterUpScale());
        waveDenty.setCtwoCenterDwon((int) diseaseScaleValueThree.getCtwoCenterDwonScale());
        waveDenty.setCtwoDeepUp((int) diseaseScaleValueThree.getCtwoDeepUpScale());
        waveDenty.setCtwoDeepDwon((int) diseaseScaleValueThree.getCtwoDeepDwonScale());
        waveFormModel.setUpTime(diseaseScaleValueTwo.getUpTimeScale());
        waveFormModel.setDownTime(diseaseScaleValueTwo.getDownTimeScale());
        waveFormModel.setSingleWaveLength((int) diseaseScaleValueTwo.getSingleWaveLengthScale());
        waveFormModel.setAThreeSpeed(diseaseScaleValueFour.getAthreeSpeedScale());
        waveFormModel.setBThreeSpeed(diseaseScaleValueFour.getBthreeSpeedScale());
        waveFormModel.setBSconeSpeed(diseaseScaleValueFour.getBsconeSpeedScale());
        waveFormModel.setDenty(waveDenty);
        return waveFormModel;
    }

}
